# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloudprojects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turns', models.IntegerField()),
                ('stack', models.IntegerField()),
                ('hands', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('roi', models.DecimalField(decimal_places=3, default='', max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='ID',
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloudprojects.User'),
        ),
    ]
