# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudprojects', '0002_auto_20171106_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hands',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='num_games',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
